name: odoo_rpc
description: Odoo RPC Client library for Dart with session changes tracking via steam.
version: 0.5.1
homepage: https://github.com/ERP-Ukraine/odoo-rpc-dart
repository: https://github.com/ERP-Ukraine/odoo-rpc-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  crypto: ^3.0.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.16.5
